# Generated by Django 4.0.3 on 2022-04-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='creditos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(default='curso no nombrado', max_length=50),
        ),
    ]
